### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [rescrv/Consus#2]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [durable_log](https://github.com/rescrv/Consus/blob/da9f9d78d0f500e7e06e93cf39fab590ac521820/txman/durable_log.cc#L102 "Destructor for durable_log")
- [leveldb_datalayer](https://github.com/rescrv/Consus/blob/da9f9d78d0f500e7e06e93cf39fab590ac521820/kvs/leveldb_datalayer.cc#L151 "Destructor for leveldb_datalayer")

**Comment by rescrv** [comment]
Thanks for the report.  There's a pull request in progress to address it.
