### ISSUE TITLE
autoconf errors

### ISSUE THREAD

**Issue by catroot** [rescrv/Consus#6]
Running autoconf throws errors:
```
configure.ac:40: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:42: error: possibly undefined macro: AM_PATH_PYTHON
configure.ac:75: error: possibly undefined macro: AC_PYTHON_DEVEL
```
How to build the consus from source?

**Comment by rescrv** [comment]
The errors indicate you are missing at least automake and autoconf-archive.

Building from git on different platforms is automatically tested.  You can find the scripts in the source tree here:  https://github.com/rescrv/Consus/tree/master/doc/install.  For example, to install on Ubuntu 16.04, follow these scripts:

 - https://github.com/rescrv/Consus/blob/master/doc/install/ubuntu16.04-git-prereqs
 - https://github.com/rescrv/Consus/blob/master/doc/install/git

When the first release comes out, this will all be included in the installation chapter of the documentation:  https://github.com/rescrv/Consus/blob/master/doc/installation.tex

Please re-open the ticket if you have trouble.

**Comment by catroot** [comment]
Running `autoreconf -ivf` makes things happen.
Thank you for pointing me.
